import { IconType } from 'react-icons'
import {
  HiOutlineArrowLeft,
  HiOutlineArrowRight,
  HiOutlinePlus,
  HiOutlinePencil,
  HiOutlineTrash,
  HiOutlineClipboardDocument,
  HiOutlineCheck,
  HiOutlineXMark,
  HiOutlineArrowRightOnRectangle,
  HiOutlineExclamationTriangle,
  HiOutlineCheckCircle,
  HiOutlineChatBubbleLeftRight,
  HiOutlineGlobeAlt,
  HiOutlineCodeBracket,
  HiOutlineFunnel,
  HiOutlineChevronRight,
  HiOutlineChevronDown,
  HiOutlineClock,
  HiOutlineComputerDesktop,
  HiOutlineExclamationCircle,
  HiOutlineArrowTopRightOnSquare,
  HiOutlineSparkles,
  HiOutlineInformationCircle,
  HiOutlineXCircle,
  HiOutlineChatBubbleOvalLeft,
  HiOutlineShieldExclamation,
  HiOutlineDocumentDuplicate,
  HiOutlineBugAnt,
} from 'react-icons/hi2'

export const iconLibrary: Record<string, IconType> = {
  arrowLeft: HiOutlineArrowLeft,
  arrowRight: HiOutlineArrowRight,
  plus: HiOutlinePlus,
  pencil: HiOutlinePencil,
  edit: HiOutlinePencil,
  trash: HiOutlineTrash,
  delete: HiOutlineTrash,
  clipboard: HiOutlineClipboardDocument,
  copy: HiOutlineDocumentDuplicate,
  check: HiOutlineCheck,
  close: HiOutlineXMark,
  logout: HiOutlineArrowRightOnRectangle,
  warning: HiOutlineExclamationTriangle,
  danger: HiOutlineShieldExclamation,
  checkCircle: HiOutlineCheckCircle,
  chat: HiOutlineChatBubbleLeftRight,
  message: HiOutlineChatBubbleOvalLeft,
  globe: HiOutlineGlobeAlt,
  code: HiOutlineCodeBracket,
  filter: HiOutlineFunnel,
  chevronRight: HiOutlineChevronRight,
  chevronDown: HiOutlineChevronDown,
  clock: HiOutlineClock,
  monitor: HiOutlineComputerDesktop,
  alert: HiOutlineExclamationCircle,
  alertCircle: HiOutlineExclamationCircle,
  openLink: HiOutlineArrowTopRightOnSquare,
  externalLink: HiOutlineArrowTopRightOnSquare,
  sparkle: HiOutlineSparkles,
  sparkles: HiOutlineSparkles,
  info: HiOutlineInformationCircle,
  xCircle: HiOutlineXCircle,
  bug: HiOutlineBugAnt,
  feedback: HiOutlineChatBubbleOvalLeft,
}

export type IconName = keyof typeof iconLibrary
