services:
  - type: web
    name: feedbackview-api
    runtime: node
    rootDir: .
    buildCommand: npm install && cd apps/api && npx prisma generate && npm run build
    startCommand: cd apps/api && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3001

  - type: web
    name: feedbackview-proxy
    runtime: node
    rootDir: .
    buildCommand: npm install && cd packages/tracker && npm run build && cd ../../apps/proxy && npx prisma generate && npm run build
    startCommand: cd apps/proxy && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3002
